name: Benchmark on Linux

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [self-hosted, Linux]
    timeout-minutes: 10
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Prepare
      shell: bash
      working-directory: ${{github.workspace}}
      run: cp ../../../small.data data/ ; cp ../../../large.data data/ ; bunzip2 small-ref.bz2 && mv small-ref ref/small.out

    - name: Benchmark
      shell: bash
      working-directory: ${{github.workspace}}
      run: python3 buildbot/runCI.py -workdir ${{github.workspace}}

